name: db
description: Brooksee DB SDK
version: 0.0.3
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  auto_size_text: ^3.0.0
  #  camera: ^0.8.1+3
  connectivity_plus: ^6.1.0
  device_info_plus: ^11.1.0
  dio: ^5.7.0
#  dio_cookie_manager: ^2.0.0
  expandable:
  just_audio: ^0.9.41
  flutter:
    sdk: flutter
  flutter_udid: ^3.0.0
  flutter_web_plugins:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.19.0
  mutex: ^3.0.1
  package_info_plus: ^8.1.0
  path: ^1.9.0
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  provider: ^6.0.0
  shared_preferences: ^2.0.18
  sqflite: ^2.4.0
  square_in_app_payments: ^1.7.6
  app_links: ^6.3.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  webview_flutter: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
#  plugin:
#    platforms:
#      android:
#        package: com.example.tracker
#        pluginClass: TrackerPlugin
#      ios:
#        pluginClass: TrackerPlugin
#      web:
#        pluginClass: TrackerWeb
#        fileName: tracker_web.dart
#
  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/unknown_user.jpg
  #assets:
  #  - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
